String.toLocaleString({

	"it": {
    "%game-intro"           : "Go <strong>JJ!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> which is itself a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Pictures taken by Jonathan & Jenna!",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'pike place',
    '%4'                    : 'spheres',
    '%8'                    : 'big kick at spheres with banana',
    '%16'                   : 'gum wall with jack',
    '%32'                   : 'stepping stones in spheres',
    '%64'                   : 'the bird\'s nest',
    '%128'                  : 'european sandwiches',
    '%256'                  : 'jj\s nest',
    '%512'                  : 'plastic campfire at day 1',
    '%1024'                 : 'where we put the gum for reference',
    '%2048'                 : 'lounging at the sky deck',
    '%4096'                 : 'the Space Needle from Kerry Park',
    '%8192'                 : 'My favorite pic of ben',
    '%p0'                   : 'pike place',
    '%p4'                   : 'spheres',
    '%p8'                   : 'big kick',
    '%p16'                  : 'gum wall jack',
    '%p32'                  : 'stepping stones',
    '%p64'                  : 'bird\'s nest',
    '%p128'                 : 'euro sandies',
    '%p256'                 : 'jj\'s nest',
    '%p512'                 : 'plastic campfire',
    '%p1024'                : 'put gum',
    '%p2048'                : 'sky deck',
    '%p4096'                : 'space needle',
    '%p8192'                : 'Ben'

	},

	"en": {
    "%game-intro"           : "Go <strong>JJ!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> which itself is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Pictures taken by Jonathan & Jenna!",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'pike place',
    '%4'                    : 'spheres',
    '%8'                    : 'big kick at spheres with banana',
    '%16'                   : 'gum wall with jack',
    '%32'                   : 'stepping stones in spheres',
    '%64'                   : 'the bird\'s nest',
    '%128'                  : 'european sandwiches',
    '%256'                  : 'jj\s nest',
    '%512'                  : 'plastic campfire at day 1',
    '%1024'                 : 'where we put the gum for reference',
    '%2048'                 : 'lounging at the sky deck',
    '%4096'                 : 'the Space Needle from Kerry Park',
    '%8192'                 : 'My favorite pic of ben',
    '%p0'                   : 'pike place',
    '%p4'                   : 'spheres',
    '%p8'                   : 'big kick',
    '%p16'                  : 'gum wall jack',
    '%p32'                  : 'stepping stones',
    '%p64'                  : 'bird\'s nest',
    '%p128'                 : 'euro sandies',
    '%p256'                 : 'jj\'s nest',
    '%p512'                 : 'plastic campfire',
    '%p1024'                : 'put gum',
    '%p2048'                : 'sky deck',
    '%p4096'                : 'space needle',
    '%p8192'                : 'Ben'

	}

});
